image: python2.7

script:
  - pip install -r requirements.txt --use-mirrors
  - py.test --tb=short tests --random --nosugar
  - pep8 models controllers tests

notify:
  email:
    recipients:
      - qingfenghello@gmail.com
